/**
 * Read-only D&D 2024 reference data — types, lazy loader, and search.
 *
 * The data lives in public/compendium/*.json (generated by scripts/build-compendium.mjs
 * from the local "Official Only 2024.xml" full PHB/DMG/MM compendium, committed) and is
 * fetched per category on first use so the ~3 MB dataset never lands in the JS bundle or
 * in GameState. Pickers copy self-contained rows into sheets; the compendium itself is
 * never persisted per-room.
 */

import type { ItemRarity, ItemType } from "./types";

export type CompendiumCategory =
  | "classes"
  | "subclasses"
  | "species"
  | "backgrounds"
  | "feats"
  | "equipment"
  | "magic-items"
  | "spells"
  | "monsters";

/** Ability-score prerequisite for adding a class (multiclassing). */
export type ClassPrereq = { abilityIds: string[]; min: number; mode: "and" | "or" };

export type CompendiumClass = {
  id: string;
  name: string;
  hitDie: number;
  primaryAbility?: string;
  /** Ability ids ("int", "wis") — map to saveProfs keys `save-${id}`. */
  saves: string[];
  armorProfs?: string[];
  weaponProfs?: string[];
  toolProfs?: string[];
  /** Skill-proficiency choice; ids match sheet skill ids ("skill-arcana"). */
  skillChoices?: { choose: number; from: string[] };
  spellcasting?: { abilityId: string; casterType: "full" | "half" | "pact" };
  subclassIds: string[];
  /** Class level at which the subclass is chosen (3 for every 2024 class). */
  subclassLevel: number;
  multiclass: {
    prereqs: ClassPrereq[];
    armorProfs?: string[];
    weaponProfs?: string[];
    toolProfs?: string[];
    skillChoice?: { choose: number; from: string[] };
  };
};

export type CompendiumSubclass = {
  id: string;
  name: string;
  classId: string;
  summary?: string;
  description: string;
};

export type CompendiumTrait = { name: string; description: string };

export type CompendiumSpecies = {
  id: string;
  name: string;
  creatureType: string;
  size: string;
  speed: number;
  traits: CompendiumTrait[];
  subspecies?: Array<{ id: string; name: string; damageType?: string; traits: CompendiumTrait[] }>;
};

export type CompendiumBackground = {
  id: string;
  name: string;
  /** The background's two skill proficiencies as sheet skill ids ("skill-insight"). */
  skills: string[];
  description: string;
};

export type CompendiumFeat = {
  id: string;
  name: string;
  /** "origin" | "general" | "fighting-style" | "epic-boon" | "maneuver" | "metamagic" | "invocation" */
  category: string;
  description: string;
};

export type CompendiumSpell = {
  id: string;
  name: string;
  /** 0 = cantrip … 9. */
  level: number;
  school: string;
  time: string;
  range: string;
  components: string;
  duration: string;
  concentration?: boolean;
  ritual?: boolean;
  /** Class ids that can cast it. */
  classes: string[];
  /** Base damage/heal dice, e.g. "8d6". */
  roll?: string;
  saveAbility?: string;
  description: string;
};

export type CompendiumEquipment = {
  id: string;
  name: string;
  category: string;
  itemType: ItemType;
  cost?: string;
  weight?: number;
  damage?: string;
  damageType?: string;
  range?: "melee" | "ranged";
  properties?: string[];
  acBase?: number;
  acDexBonus?: boolean;
  acMaxBonus?: number;
  strMin?: number;
  stealthDisadvantage?: boolean;
  description?: string;
};

export type CompendiumMagicItem = {
  id: string;
  name: string;
  itemType: ItemType;
  category: string;
  rarity: ItemRarity | "varies";
  /** Original rarity line when it can't collapse to one value. */
  rarityText?: string;
  attunement?: boolean;
  /** Concrete variant of a generic parent (e.g. "+1 Longsword"). */
  variant?: boolean;
  hasVariants?: boolean;
  description: string;
};

export type CompendiumMonsterAction = {
  name: string;
  description: string;
  toHit?: number;
  damage?: string;
  damageType?: string;
  uses?: { current: number; max: number };
};

export type CompendiumMonster = {
  id: string;
  name: string;
  size: string;
  type: string;
  alignment?: string;
  ac: number;
  acNote?: string;
  hp: number;
  hitDice?: string;
  hitDiceCount?: number;
  hitDie?: string;
  walkSpeed: number;
  speedLine: string;
  abilities: Record<string, number>;
  initiative?: number;
  /** Stat-block save bonuses keyed by ability id ("dex": 3). */
  saves: Record<string, number>;
  /** Stat-block skill bonuses keyed by sheet skill id ("skill-stealth": 6). */
  skills: Record<string, number>;
  senses?: string;
  languages?: string;
  cr: string;
  xp?: number;
  profBonus: number;
  /** Book citation, e.g. "Monster Manual 2024 p. 143". */
  source?: string;
  vulnerabilities?: string[];
  resistances?: string[];
  immunities?: string[];
  conditionImmunities?: string[];
  traits?: CompendiumTrait[];
  actions?: CompendiumMonsterAction[];
  bonusActions?: CompendiumMonsterAction[];
  reactions?: CompendiumMonsterAction[];
  legendary?: CompendiumMonsterAction[];
};

export type CompendiumMeta = {
  ruleset: string;
  license: string;
  attribution: string;
  source?: { file: string; format: string };
  counts: Record<string, number>;
  generated: string;
};

/** Shown wherever compendium content is browsed. */
export const COMPENDIUM_ATTRIBUTION =
  "Compendium data from the D&D 2024 core rulebooks (Wizards of the Coast) — for private use at this table, not for redistribution.";

const cache = new Map<CompendiumCategory | "meta", Promise<unknown>>();

async function fetchCompendium(name: string): Promise<unknown> {
  const res = await fetch(`/compendium/${name}.json`);
  if (!res.ok) throw new Error(`Failed to load compendium ${name} (${res.status})`);
  return res.json();
}

/** Lazy-loads a category on first use; the promise is cached (cleared on failure so a retry refetches). */
export function loadCompendium<T>(category: CompendiumCategory): Promise<T[]> {
  let promise = cache.get(category);
  if (!promise) {
    promise = fetchCompendium(category).catch((err) => {
      cache.delete(category);
      throw err;
    });
    cache.set(category, promise);
  }
  return promise as Promise<T[]>;
}

export const loadClasses = () => loadCompendium<CompendiumClass>("classes");
export const loadSubclasses = () => loadCompendium<CompendiumSubclass>("subclasses");
export const loadSpecies = () => loadCompendium<CompendiumSpecies>("species");
export const loadBackgrounds = () => loadCompendium<CompendiumBackground>("backgrounds");
export const loadFeats = () => loadCompendium<CompendiumFeat>("feats");
export const loadEquipment = () => loadCompendium<CompendiumEquipment>("equipment");
export const loadMagicItems = () => loadCompendium<CompendiumMagicItem>("magic-items");
export const loadSpells = () => loadCompendium<CompendiumSpell>("spells");
export const loadMonsters = () => loadCompendium<CompendiumMonster>("monsters");

/**
 * Substring search matching the RowTable filter idiom (trimmed, case-insensitive
 * includes). Name-prefix matches sort first, then name matches, then extra-text
 * matches; ties stay alphabetical (rows arrive pre-sorted by id).
 */
export function searchCompendium<T extends { name: string }>(
  rows: T[],
  query: string,
  extraText?: (row: T) => string,
): T[] {
  const q = query.trim().toLowerCase();
  if (!q) return rows;
  const ranked: Array<{ row: T; rank: number }> = [];
  for (const row of rows) {
    const name = row.name.toLowerCase();
    if (name.startsWith(q)) ranked.push({ row, rank: 0 });
    else if (name.includes(q)) ranked.push({ row, rank: 1 });
    else if (extraText && extraText(row).toLowerCase().includes(q)) ranked.push({ row, rank: 2 });
  }
  return ranked.sort((a, b) => a.rank - b.rank).map((r) => r.row);
}
