import type {
  DieResult,
  LogEntry,
  RollCategory,
  RollPart,
  RollRecord,
} from "./types";

/** The roll variant of the unified log entry. */
export type RollLogEntry = Extract<LogEntry, { kind: "roll" }>;

/** Expected average of a fair d20 — the baseline every "luck" number compares against. */
export const D20_MEAN = 10.5;

/** Max archived label length. */
export const MAX_ROLL_LABEL = 48;

/** Plain-English category names for the Stats page (beginner-friendly). */
export const CATEGORY_LABELS: Record<RollCategory, string> = {
  check: "Checks",
  save: "Saving throws",
  attack: "Attacks",
  damage: "Damage",
  initiative: "Turn order",
  death: "Death saves",
  coin: "Coin flips",
  other: "Other rolls",
};

const DIE_LABEL_RE = /^d(\d+)$/i;

function isCoinEntry(entry: RollLogEntry): boolean {
  const expr = entry.roll.expression;
  if (/^coin flip/i.test(expr) || /^\d+ coins?\b/i.test(expr)) {
    return true;
  }
  return (entry.roll.parts ?? []).some(
    (part) => part.label === "Heads" || part.label === "Tails",
  );
}

/**
 * What a roll was for. Prefers the server-assigned `category`; legacy/freeform rolls
 * fall back to label heuristics (labels like "Stealth check" / "Longsword damage"
 * are server-generated by resolveCheck, so the patterns are stable).
 */
export function deriveRollCategory(entry: RollLogEntry): RollCategory {
  if (entry.category) {
    return entry.category;
  }
  if (isCoinEntry(entry)) {
    return "coin";
  }
  const label = entry.label ?? "";
  if (/^death saving throw/i.test(label)) {
    return "death";
  }
  if (/\binitiative\b/i.test(label)) {
    return "initiative";
  }
  if (/damage/i.test(label)) {
    return "damage";
  }
  if (/\bsave\b|saving throw/i.test(label)) {
    return "save";
  }
  if (/attack/i.test(label)) {
    return "attack";
  }
  if (/\bcheck\b|\btools?\b/i.test(label)) {
    return "check";
  }
  return "other";
}

function diceFromParts(parts: RollPart[]): DieResult[] {
  const dice: DieResult[] = [];
  for (const part of parts) {
    if (part.kind !== "die") {
      continue;
    }
    const match = part.label ? DIE_LABEL_RE.exec(part.label) : null;
    if (match) {
      dice.push([Number(match[1]), part.value]);
    } else if (part.label === "coin") {
      // Mixed 3D pools label coin faces "coin" (all-coin throws use Heads/Tails flats).
      dice.push([2, part.value]);
    } else {
      dice.push([0, part.value]);
    }
  }
  return dice;
}

/** Expands "2d6+1d8+3" into per-die side counts, zipped against the rolled values. */
function diceFromExpression(expression: string, rolls: number[]): DieResult[] {
  const sides: number[] = [];
  for (const match of expression.matchAll(/(\d+)\s*d\s*(\d+)/gi)) {
    const count = Math.min(200, Number(match[1]));
    for (let i = 0; i < count; i += 1) {
      sides.push(Number(match[2]));
    }
  }
  if (sides.length === rolls.length) {
    return rolls.map((value, i) => [sides[i], value]);
  }
  // Unparsable or adv/dis-mangled expression: keep the values, mark sides unknown.
  return rolls.map((value) => [0, value]);
}

/**
 * Builds the slim archive record for a roll log entry. Returns null for masked
 * player-side copies (they carry no real values).
 */
export function buildRollRecord(entry: RollLogEntry): RollRecord | null {
  if (entry.masked) {
    return null;
  }
  const roll = entry.roll;
  const cat = deriveRollCategory(entry);
  let dice: DieResult[];
  if (cat === "coin") {
    dice = roll.rolls.map((value) => [2, value]);
  } else {
    const parts = roll.parts ?? [];
    dice = parts.some((part) => part.kind === "die")
      ? diceFromParts(parts)
      : diceFromExpression(roll.expression, roll.rolls);
  }
  const diceSum = dice.reduce((sum, [, value]) => sum + value, 0);
  const mod = roll.total - diceSum;
  const record: RollRecord = {
    id: roll.id,
    t: roll.timestamp,
    who: roll.rollerId,
    name: entry.actor?.name || roll.rollerName,
    cat,
    dice,
    mod,
    total: roll.total,
  };
  if (roll.adv) {
    record.adv = roll.adv;
    // Recover the discarded natural d20 for single-d20 adv/dis rolls (same modifier
    // applied to both attempts), so the fairness histogram can stay flat.
    if (dice.length === 1 && dice[0][0] === 20 && roll.otherTotal !== undefined) {
      const other = roll.otherTotal - mod;
      if (other >= 1 && other <= 20) {
        record.other = other;
      }
    }
  }
  if (roll.crit) {
    record.crit = true;
  }
  if (entry.dmOnly) {
    record.secret = true;
  }
  if (entry.label) {
    record.label = entry.label.slice(0, MAX_ROLL_LABEL);
  }
  return record;
}

/** Kept natural d20 values of a record (empty for coins/damage/etc). */
export function keptD20s(record: RollRecord): number[] {
  return record.dice.filter(([sides]) => sides === 20).map(([, value]) => value);
}

export type RollerSummary = {
  who: string;
  /** Display name from the most recent record (page may override from live slots). */
  name: string;
  count: number;
  d20Count: number;
  /** Average natural d20 (bare die, before bonuses); null under `minD20s`. */
  avgD20: number | null;
  /** avgD20 − 10.5: above zero = lucky, below = unlucky. */
  luck: number | null;
  /** Average roll result including bonuses (coins excluded); null with no rolls. */
  avgTotal: number | null;
  nat20: number;
  nat1: number;
  crits: number;
  advCount: number;
  disCount: number;
  coinCount: number;
};

/**
 * Per-roller aggregate rows for the "Who's been lucky?" table. Averages need at
 * least `minD20s` kept d20s — tiny samples read as wild luck swings otherwise.
 */
export function summarizeRollers(records: RollRecord[], minD20s = 1): RollerSummary[] {
  const map = new Map<string, RollerSummary & { d20Sum: number; totalSum: number; totalCount: number; lastT: number }>();
  for (const record of records) {
    let row = map.get(record.who);
    if (!row) {
      row = {
        who: record.who,
        name: record.name,
        count: 0,
        d20Count: 0,
        avgD20: null,
        luck: null,
        avgTotal: null,
        nat20: 0,
        nat1: 0,
        crits: 0,
        advCount: 0,
        disCount: 0,
        coinCount: 0,
        d20Sum: 0,
        totalSum: 0,
        totalCount: 0,
        lastT: 0,
      };
      map.set(record.who, row);
    }
    row.count += 1;
    if (record.t >= row.lastT) {
      row.lastT = record.t;
      row.name = record.name;
    }
    if (record.cat === "coin") {
      row.coinCount += 1;
    } else {
      row.totalSum += record.total;
      row.totalCount += 1;
    }
    for (const value of keptD20s(record)) {
      row.d20Count += 1;
      row.d20Sum += value;
      if (value === 20) {
        row.nat20 += 1;
      }
      if (value === 1) {
        row.nat1 += 1;
      }
    }
    if (record.crit) {
      row.crits += 1;
    }
    if (record.adv === "adv") {
      row.advCount += 1;
    }
    if (record.adv === "dis") {
      row.disCount += 1;
    }
  }
  const rows: RollerSummary[] = [];
  for (const row of map.values()) {
    const { d20Sum, totalSum, totalCount, lastT: _lastT, ...summary } = row;
    if (summary.d20Count >= minD20s && summary.d20Count > 0) {
      summary.avgD20 = d20Sum / summary.d20Count;
      summary.luck = summary.avgD20 - D20_MEAN;
    }
    if (totalCount > 0) {
      summary.avgTotal = totalSum / totalCount;
    }
    rows.push(summary);
  }
  return rows;
}

/**
 * Counts of natural d20 results, faces 1-20 (index 0 = face 1). With
 * `includeDiscarded`, the die dropped by advantage/disadvantage counts too —
 * keeping only the winners would legitimately skew the shape, so this is the
 * honest "are the dice fair?" view.
 */
export function d20Histogram(records: RollRecord[], includeDiscarded = true): number[] {
  const bins = new Array<number>(20).fill(0);
  for (const record of records) {
    for (const value of keptD20s(record)) {
      if (value >= 1 && value <= 20) {
        bins[value - 1] += 1;
      }
    }
    if (includeDiscarded && record.other !== undefined) {
      bins[record.other - 1] += 1;
    }
  }
  return bins;
}

export type DieTypeStats = {
  sides: number;
  count: number;
  avg: number;
  /** A fair die of this size averages (sides + 1) / 2. */
  expected: number;
};

/** Per-die-size usage + averages (coins excluded — they get their own tile). */
export function dieTypeBreakdown(records: RollRecord[]): DieTypeStats[] {
  const map = new Map<number, { count: number; sum: number }>();
  for (const record of records) {
    if (record.cat === "coin") {
      continue;
    }
    for (const [sides, value] of record.dice) {
      const cell = map.get(sides) ?? { count: 0, sum: 0 };
      cell.count += 1;
      cell.sum += value;
      map.set(sides, cell);
    }
  }
  return [...map.entries()]
    .map(([sides, cell]) => ({
      sides,
      count: cell.count,
      avg: cell.sum / cell.count,
      expected: sides > 0 ? (sides + 1) / 2 : 0,
    }))
    .sort((a, b) => b.count - a.count);
}

export type DayBucket = {
  /** Local-time day key, "YYYY-MM-DD". */
  day: string;
  /** Start of that local day, for label formatting. */
  t: number;
  /** Roll counts per roller id. */
  counts: Record<string, number>;
  total: number;
};

function dayKeyOf(t: number): { day: string; start: number } {
  const date = new Date(t);
  const pad = (n: number) => String(n).padStart(2, "0");
  const day = `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}`;
  const start = new Date(date.getFullYear(), date.getMonth(), date.getDate()).getTime();
  return { day, start };
}

/** Rolls grouped by local calendar day (no session concept exists — days stand in). */
export function rollsByDay(records: RollRecord[]): DayBucket[] {
  const map = new Map<string, DayBucket>();
  for (const record of records) {
    const { day, start } = dayKeyOf(record.t);
    let bucket = map.get(day);
    if (!bucket) {
      bucket = { day, t: start, counts: {}, total: 0 };
      map.set(day, bucket);
    }
    bucket.counts[record.who] = (bucket.counts[record.who] ?? 0) + 1;
    bucket.total += 1;
  }
  return [...map.values()].sort((a, b) => a.t - b.t);
}

/** Counts per category, in ROLL_CATEGORIES order, zero-count categories dropped. */
export function categoryBreakdown(records: RollRecord[]): Array<{ cat: RollCategory; count: number }> {
  const map = new Map<RollCategory, number>();
  for (const record of records) {
    map.set(record.cat, (map.get(record.cat) ?? 0) + 1);
  }
  const order: RollCategory[] = [
    "check",
    "save",
    "attack",
    "damage",
    "initiative",
    "death",
    "coin",
    "other",
  ];
  return order
    .filter((cat) => (map.get(cat) ?? 0) > 0)
    .map((cat) => ({ cat, count: map.get(cat) ?? 0 }));
}
